services:
  - type: web
    name: sankalp-evaluator-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_EMAILS
        value: rohitgupta6294@gmail.com,rahulgupta6294@gmail.com
      - key: FIREBASE_PROJECT_ID
        value: sankalp-learning-5442f
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
